name: Main branch release
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
jobs:
  generateVersion:
    name: "Generate release"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate version
        id: generate-version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          format: "${major}.${minor}.${patch}"
      - name: Create tag and push
        run: git tag ${{ steps.generate-version.outputs.version }} && git push --tags
      - name: Generate release
        uses: Roang-zero1/github-create-release-action@v3.0.1
        with:
          created_tag: "${{ steps.generate-version.outputs.version_tag }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
